### ISSUE TITLE
EN Translation

### ISSUE THREAD

**Issue by Spokeek** [Narazaka/AvatarMenuCreaterForMA#11]
I'm using this tool as my main modular toogle tool, but having to pull my translating app for every menu is a bit of pain. May i require a translation of the tool in english ?

**Comment by Narazaka** [comment]
@Spokeek Translation (DeepL) is now available in 1.15.0

**Comment by Spokeek** [comment]
Lovely. Thank you a lot

**Comment by Narazaka** [comment]
and it had a bug. please update to 1.15.1
