### ISSUE TITLE
Advance Menu only apears for first object

### ISSUE THREAD

**Issue by Spokeek** [Narazaka/AvatarMenuCreaterForMA#13]
I was trying to use the Advanced option to be able to toggle two kinds of shirts, so when i toggle one, the other one is off, but if i turn it off, it doesn't turn on the other one.

But the advanced menu **only appears for the first object**
![image](https://github.com/Narazaka/AvatarMenuCreaterForMA/assets/4519853/8149b2ac-a429-49ea-9e4d-82b1428e2e4f)

Also mentioning the **translation** turns into "Anvanced" instead of "Advanced"

**Comment by Narazaka** [comment]
advanced settings are showed only when the object is controled.

**Comment by Spokeek** [comment]
So dumb i am, how didn't i notice that. Sorry
