### ISSUE TITLE
[1.17.0]Unity2019でコンパイルエラーが起きる模様

### ISSUE THREAD

**Issue by Azukimochi** [Narazaka/AvatarMenuCreaterForMA#15]
タイトル通りです。  

コンソールエラー：
> Packages\net.narazaka.vrchat.avatar-menu-creater-for-ma\Components\Editor\ParameterProviders\AvatarMenuCreatorBaseParameterProvider.cs(22,70): error CS0122: 'AllowNullAttribute' is inaccessible due to its protection level

**Comment by Narazaka** [comment]
すんませんなおしました
